---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "uws-api-server.fullname" . }}-butler-secret
  namespace: uws
  labels:
    app.kubernetes.io/name: {{ include "uws-api-server.name" . }}
spec:
  path: {{ required "vaultPathPrefix must be set" .Values.vaultPathPrefix }}/{{ required "butler.secretKey must be set" .Values.butler.secretKey }}
  type: Opaque
