targetCluster: "summit"
hostname: summit-lsp.lsst.codes
image:
  tag: latest
vaultPathPrefix: secret/k8s_operator/summit-lsp.lsst.codes
butlerPg:
  secretKey: butler-secret
  containerPath: /home/lsst/.lsst
  dbUser: oods
workingVolume:
  name: job-files
  server: nfs1.cp.lsst.org
  exportPath: "/scratch"
  claimName: uws-server-pvc
  mountPath: "/uws"
  subPath: "uws"
volumes:
- name: project
  server: nfs1.cp.lsst.org
  claimName: project-pvc
  mountPath: "/project"
  exportPath: "/project"
  subPath: ""
  readOnly: false
- name: repo-latiss
  server: auxtel-archiver.cp.lsst.org
  claimName: repo-latiss-pvc
  mountPath: "/repo/LATISS"
  exportPath: "/repo/LATISS"
  subPath: ""
  readOnly: false
- name: repo-comcam
  server: comcam-archiver.cp.lsst.org
  claimName: repo-comcam-pvc
  mountPath: "/repo/LSSTComCam"
  exportPath: "/repo/LSSTComCam"
  subPath: ""
  readOnly: false
- name: data-auxtel
  server: auxtel-archiver.cp.lsst.org
  claimName: data-auxtel-pvc
  mountPath: "/data/lsstdata/base/auxtel"
  exportPath: "/lsstdata/base/auxtel"
  subPath: ""
  readOnly: true
- name: data-comcam
  server: comcam-archiver.cp.lsst.org
  claimName: data-comcam-pvc
  mountPath: "/data/lsstdata/base/comcam"
  exportPath: "/lsstdata/base/comcam"
  subPath: ""
  readOnly: true
