uws-api-server:
  targetCluster: "summit"
  hostname: summit-lsp.lsst.codes
  image:
    tag: v1.0.0
  workingVolume:
    name: job-files
    server: nfs1.cp.lsst.org
    exportPath: "/scratch"
    claimName: uws-server-pvc
    mountPath: "/uws"
    subPath: "uws"
  volumes:
  - name: project
    server: nfs1.cp.lsst.org
    claimName: project-pvc
    mountPath: "/project"
    exportPath: "/project"
    subPath: ""
    readOnly: false
  - name: home
    server: nfs1.cp.lsst.org
    claimName: home-pvc
    mountPath: "/jhome"
    exportPath: "/jhome"
    subPath: ""
    readOnly: false
  - name: repo-latiss
    server: atarchiver.cp.lsst.org
    claimName: repo-latiss-pvc
    mountPath: "/repo/LATISS"
    exportPath: "/repo/LATISS"
    subPath: ""
    readOnly: false
  - name: repo-comcam
    server: comcam-arctl01.cp.lsst.org
    claimName: repo-comcam-pvc
    mountPath: "/repo/LSSTComCam"
    exportPath: "/repo/LSSTComCam"
    subPath: ""
    readOnly: false
  - name: data-auxtel
    server: atarchiver.cp.lsst.org
    claimName: data-auxtel-pvc
    mountPath: "/data/lsstdata/base/auxtel"
    exportPath: "/lsstdata/base/auxtel"
    subPath: ""
    readOnly: true
  - name: data-comcam
    server: comcam-arctl01.cp.lsst.org
    claimName: data-comcam-pvc
    mountPath: "/data/lsstdata/base/comcam"
    exportPath: "/lsstdata/base/comcam"
    subPath: ""
    readOnly: true
